language: php

php:
  - hhvm

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: polyfill='true'
    - php: 7.1
      env: polyfill='false'

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
